<a href="https://colab.research.google.com/github/09-ashish/DSA-CaseStudies/blob/main/Data_Acquisition_Casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import pandas as pd
import os
import time
from datetime import datetime
import numpy as np
import requests
import sqlite3

**Data Extraction**

In [ ]:
#task1
population = pd.read_csv("/content/population.csv")
print(population.head(5))
print(population.shape)
print(population.dtypes)

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525
(25, 2)
country       object
population     int64
dtype: object

In [ ]:
#task2
gdp=pd.read_excel("/content/gdp.xlsx")
print(gdp.columns)
print(gdp.dtypes)

Index(['Country', 'GDP'], dtype='object')
Country    object
GDP         int64
dtype: object

In [ ]:
#task3
in_users=pd.read_json("/content/internet_users.json")
users=pd.DataFrame(in_users)
users.head()

         country  internet_users
0  United States       312000000
1          China      1080000000
2          India       850000000
3          Japan       118000000
4        Germany        79000000

In [ ]:
#task 5
literacy=pd.read_xml("/content/literacy_rate.xml")
literacy=pd.DataFrame(literacy)
literacy.head()

            name  literacy_rate
0  United States           99.0
1          China           97.2
2          India           77.7
3          Japan           99.0
4        Germany           99.0

In [ ]:
#task 5
#population
print(f"missing values: {population.isnull().sum()}")
print(f"duplicate values: {population.duplicated().sum()}")

#gdp
print(f"missing values: {gdp.isnull().sum()}")
print(f"duplicate values: {gdp.duplicated().sum()}")

#internet users
print(f"missing values: {users.isnull().sum()}")
print(f"duplicate values: {users.duplicated().sum()}")

#literacy
print(f"missing values: {literacy.isnull().sum()}")
print(f"duplicate values: {literacy.duplicated().sum()}")

missing values: country       0
population    0
dtype: int64
duplicate values: 0
missing values: Country    0
GDP        0
dtype: int64
duplicate values: 0
missing values: country           0
internet_users    0
dtype: int64
duplicate values: 0
missing values: name             0
literacy_rate    0
dtype: int64
duplicate values: 0

**Data Transformation**

In [ ]:
#task 6
gdp.rename(columns={'Country':'country'}, inplace=True)
literacy.rename(columns={'name':'country'}, inplace=True)

In [ ]:
print(population.columns)
print(gdp.columns)
print(users.columns)
print(literacy.columns)

Index(['country', 'population'], dtype='object')
Index(['country', 'GDP'], dtype='object')
Index(['country', 'internet_users'], dtype='object')
Index(['country', 'literacy_rate'], dtype='object')

In [ ]:
print(population.dtypes)
print(gdp.dtypes)
print(users.dtypes)
print(literacy.dtypes)

country       object
population     int64
dtype: object
country    object
GDP         int64
dtype: object
country           object
internet_users     int64
dtype: object
country           object
literacy_rate    float64
dtype: object

In [37]:
#task 7
#task 8

data_df=population.merge(gdp,on='country')\
.merge(users,on='country')\
.merge(literacy,on='country')

data_df.head()

         country  population       GDP  internet_users  literacy_rate
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

In [39]:
#task 9
data_df['Internet_Penetration(%)']=((data_df['internet_users'] / data_df['population']) * 100).round(2)
data_df['GDP Per Capita']= (data_df['GDP'] / data_df['population']).round(2)

data_df.head()

,country,population,GDP,internet_users,literacy_rate,Internet_Penetration(%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

**Load Data**

In [43]:
#task 10

conn = sqlite3.connect('country_data.db')
data_df.to_sql('country_statistics',conn, if_exists='replace',index=False)
cursor=conn.cursor()

In [47]:
#task 11
query='''select * from country_statistics limit 5'''
cursor.execute(query)
countries=cursor.fetchall()

for row in countries:
  print(row)

('United States', 331002651, 30500000, 312000000, 99.0, 94.26, 0.09)
('China', 1411778724, 19230000, 1080000000, 97.2, 76.5, 0.01)
('India', 1380004385, 4187000, 850000000, 77.7, 61.59, 0.0)
('Japan', 125836021, 4180000, 118000000, 99.0, 93.77, 0.03)
('Germany', 83240525, 4744000, 79000000, 99.0, 94.91, 0.06)

**Data Analysis using Pandas**

In [49]:
#1
data_df.sort_values(by=['GDP'],ascending=False).head(5)[['country','GDP']]

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

In [50]:
#2
data_df.sort_values(by=['population'],ascending=False).head(5)[['country','population']]

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

In [52]:
#3
print(f"average literacy rate : {data_df['literacy_rate'].mean()}")

average literacy rate : 97.248

In [55]:
#4
data_df[data_df['literacy_rate'] > 90][['country']]

           country
0    United States
1            China
3            Japan
4          Germany
5   United Kingdom
6           France
7            Italy
8           Canada
9        Australia
10          Brazil
11          Russia
12     South Korea
13           Spain
14          Mexico
15       Indonesia
16    Saudi Arabia
17          Turkey
18    South Africa
19       Argentina
20     Netherlands
21     Switzerland
22          Sweden
23          Norway
24       Singapore

In [57]:
#5
data_df[data_df['Internet_Penetration(%)'] > 70][['country','Internet_Penetration(%)']]

           country  Internet_Penetration(%)
0    United States                    94.26
1            China                    76.50
3            Japan                    93.77
4          Germany                    94.91
5   United Kingdom                    97.22
6           France                    94.98
7            Italy                    92.62
8           Canada                    94.72
9        Australia                    93.43
10          Brazil                    85.15
11          Russia                    85.65
12     South Korea                    96.56
13           Spain                    94.11
14          Mexico                    79.11
15       Indonesia                    77.51
16    Saudi Arabia                    97.66
17          Turkey                    81.81
18    South Africa                    72.50
19       Argentina                    90.72
20     Netherlands                    97.47
21     Switzerland                    98.21
22          Sweden                    97.55
23          Norway                    97.76
24       Singapore                    95.72

In [59]:
#6
data_df.sort_values(by=['GDP Per Capita'],ascending=False).head(5)[['country','GDP Per Capita']]

          country  GDP Per Capita
21    Switzerland            0.11
23         Norway            0.11
24      Singapore            0.09
0   United States            0.09
9       Australia            0.07

In [60]:
#7
print(f"Total Population: {data_df['population'].sum()}")

Total Population: 4720039725

In [61]:
#8
print(f"Average Internet penetration : {data_df['Internet_Penetration(%)'].mean()}")

Average Internet penetration : 89.6596

In [63]:
#9
data_df.sort_values(by=['internet_users'],ascending=False).head(1)[['country','internet_users']]

  country  internet_users
1   China      1080000000

In [65]:
#10
print(f"The correlation between literacy rate and internet penetration is {data_df['literacy_rate'].corr(data_df['Internet_Penetration(%)'])}")

The correlation between literacy rate and internet penetration is 0.77279756813985

**Data Analysis Using SQL**

In [67]:
#11
cursor.execute("select country,GDP from country_statistics order by GDP desc limit 5")

top_gdp_countries = cursor.fetchall()

for row in top_gdp_countries:
    print(row)

('United States', 30500000)
('China', 19230000)
('Germany', 4744000)
('India', 4187000)
('Japan', 4180000)

In [68]:
#12
query='''
select avg(literacy_rate)
from country_statistics'''

cursor.execute(query)
top_gdp_countries = cursor.fetchall()

for row in top_gdp_countries:
    print(row)

(97.24799999999999,)

In [69]:
#13
query='''
select country,literacy_rate
from country_statistics
where literacy_rate > 90
order by literacy_rate desc '''

cursor.execute(query)
top_gdp_countries = cursor.fetchall()

for row in top_gdp_countries:
    print(row)

('Norway', 100.0)
('Russia', 99.7)
('Argentina', 99.1)
('United States', 99.0)
('Japan', 99.0)
('Germany', 99.0)
('United Kingdom', 99.0)
('France', 99.0)
('Italy', 99.0)
('Canada', 99.0)
('Australia', 99.0)
('Netherlands', 99.0)
('Switzerland', 99.0)
('Sweden', 99.0)
('South Korea', 98.8)
('Spain', 98.6)
('Singapore', 97.5)
('Saudi Arabia', 97.3)
('China', 97.2)
('Turkey', 96.7)
('Indonesia', 96.0)
('Mexico', 95.4)
('South Africa', 95.0)
('Brazil', 93.2)

In [73]:
#14
query='''
select country,"Internet_Penetration(%)"
from country_statistics
order by 'Internet_Penetration(%)' desc
limit 5'''

cursor.execute(query)
top_gdp_countries = cursor.fetchall()

for row in top_gdp_countries:
    print(row)

('United States', 94.26)
('China', 76.5)
('India', 61.59)
('Japan', 93.77)
('Germany', 94.91)

In [74]:

query = '''
ALTER TABLE country_statistics
RENAME COLUMN `Internet_Penetration(%)` TO internet_penetration;
'''

cursor.execute(query)
conn.commit()

In [80]:
query = '''
ALTER TABLE country_statistics
RENAME COLUMN `GDP Per Capita` TO GDP_per_capita;
'''

cursor.execute(query)
conn.commit()

In [76]:
#15
query='''
select sum(population)
from country_statistics
'''
cursor.execute(query)
top_internet_countries = cursor.fetchall()

for row in top_internet_countries:
    print(row)

(4720039725,)

In [82]:
#16
query='''
select country,GDP_per_capita
from country_statistics
order by GDP_per_capita desc
limit 1
'''

cursor.execute(query)
top_internet_countries = cursor.fetchall()

for row in top_internet_countries:
    print(row)

('Switzerland', 0.11)

In [84]:
#18
query='''
select country,GDP_per_capita
from country_statistics
order by GDP_per_capita desc
limit 10
'''
cursor.execute(query)
top_internet_countries = cursor.fetchall()

for row in top_internet_countries:
    print(row)

('Switzerland', 0.11)
('Norway', 0.11)
('United States', 0.09)
('Singapore', 0.09)
('Australia', 0.07)
('Netherlands', 0.07)
('Germany', 0.06)
('United Kingdom', 0.06)
('Canada', 0.06)
('Sweden', 0.06)

In [85]:
#17
data_df.to_csv('country_statistics.csv', index=False)
print("Dataset Successfully Exported")

Dataset Successfully Exported

**Summary**
*  the data sources used are population.csv,gdp.xlsx,literacy_rate.xml and internet_users.json

* data cleaning: checked for null and duplicated values. renamed the country name columns of all datasets as country.


* transformations:created two new columns Internet_penetration % and GDP per capita

* database loading: created a table country_statistics from the Merged DataFrame.

* key Insights: Switzerland has the highest GDP per capita,united states has the highest internet pentration rate even tho china has the most number of internet users. norway has a literacy rate of 100 and 24 countries have literacy rate above 90.